{% set name = "pytorch-metric-learning" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorch-metric-learning-{{ version }}.tar.gz
  sha256: e7bde95e7e20ace9c3f2f939896661821346e2e0acdca9af02d133f7b0e2191e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - numpy
    - scikit-learn
    - tqdm
    - pytorch >=1.6.0

test:
  imports:
    - pytorch_metric_learning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KevinMusgrave/pytorch-metric-learning
  summary: The easiest way to use deep metric learning in your application. Modular, flexible, and extensible. Written in PyTorch.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - KevinMusgrave
